// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {lib} from '../models';

export function Cancel():Promise<void>;

export function LoadTest(arg1:main.LoadTestConfig):Promise<lib.PerformanceMetrics>;
