name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows/amd64, windows/arm64, darwin/amd64, darwin/arm64, linux/amd64, linux/arm64]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: |
        wails build -platform ${{ matrix.platform }} -o ${{ runner.temp }}/loadr-${{ matrix.platform }}
    - uses: actions/upload-artifact@v2
      with:
        name: loadr-${{ matrix.platform }}
        path: ${{ runner.temp }}/loadr-${{ matrix.platform }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./artifacts/*
        asset_name: loadr-${{ matrix.platform }}
        asset_content_type: application/octet-stream